---
- name: Install CouchDB Repo
  template:
    src: templates/bintray-apache-couchdb-rpm.repo.j2
    dest: /etc/yum.repos.d/bintray-apache-couchdb-rpm.repo

- name: Install CouchDB
  yum:
    name: couchdb
    state: latest
  notify: Restart CouchDB

- name: Create CouchDB Log Directory
  file:
    path: /var/log/couchdb
    state: directory
    owner: couchdb
    group: couchdb

- name: Create CouchDB Data Directory
  file:
    path: /var/lib/couchdb
    state: directory
    owner: couchdb
    group: couchdb

- name: Create CouchDB Service
  copy:
    src: files/couchdb.service
    dest: /lib/systemd/system/couchdb.service

- name: Create CouchDB Admin Password Hash Fact
  shell: "echo -n {{ couch_password }}salt | sha1sum | awk '{print \"-hashed-\"$1\",salt\"}'"
  register: couch_hash
  changed_when: false
  check_mode: no

- name: Create CouchDB local.ini
  template:
    src: local.ini.j2
    dest: /opt/couchdb/etc/local.ini
    owner: couchdb
    group: couchdb
  notify: Restart CouchDB

- name: Create CouchDB vm.args
  template:
    src: vm.args.j2
    dest: /opt/couchdb/etc/vm.args
  notify: Restart CouchDB

- name: Create CouchDB Logging File
  template:
    src: files/10-filelog.ini
    dest: /opt/couchdb/etc/local.d/10-logfile.ini
  notify: Restart CouchDB  

- name: Start and Enable CouchDB
  service:
    name: couchdb
    state: started
    daemon_reload: yes
    enabled: yes

- name: Cluster CouchDB
  couchcluster:
    current_node: "{{ ansible_fqdn }}"
    node_1: "{{ groups['couchdb'][0] }}"
    couch_user: "{{ couch_user }}"
    couch_password: "{{ couch_password }}"
  notify: Restart CouchDB

