---
- name: Install Kamailio
  yum:
    name: kazoo-kamailio
    state: latest
  notify: Restart Kamailio

- name: Stop and Disable Default Kamailio
  service:
    name: kamailio
    state: stopped
    enabled: no

- name: Create Kamailio local.cfg
  template:
    src: local.cfg.j2
    dest: /etc/kazoo/kamailio/local.cfg
  notify: Restart Kamailio

- name: Start and Enable Kazoo Kamailio
  service:
    name: kazoo-kamailio
    state: started
    enabled: yes

- name: Allow Kamailio SIP TCP
  firewalld:
    port: 5060/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Kamailio SIP UDP
  firewalld:
    port: 5060/udp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Kamailio TLS TCP
  firewalld:
    port: 5061/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Kamailio TLS UDP
  firewalld:
    port: 5061/udp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Kamailio WebRTC TCP
  firewalld:
    port: 5064/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Kamailio WebRTC UDP
  firewalld:
    port: 5064/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Kamailio WebRTC SSL TCP
  firewalld:
    port: 5064/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Kamailio WebRTC SSL UDP
  firewalld:
    port: 5064/udp
    permanent: true
    immediate: true
    state: enabled

